// Generates the exact chi-squared 0.95 quantile table used by official Open_VINS.
// Values are emitted as C99 hex-float literals so the embedded table is
// bit-identical to boost::math::quantile(chi_squared(dof), 0.95).
#include <boost/math/distributions/chi_squared.hpp>
#include <cstdio>
int main() {
  std::printf("// GENERATED by tests/gen_chi2_table.cpp -- do not hand-edit.\n");
  std::printf("// Exact boost::math::quantile(boost::math::chi_squared(dof), 0.95),\n");
  std::printf("// matching official Open_VINS UpdaterMSCKF's chi_squared_table.\n");
  std::printf("// Hex-float literals so the values are bit-identical, not rounded.\n");
  std::printf("#pragma once\n\nnamespace msckf {\n\n");
  std::printf("constexpr int CHI2_TABLE_SIZE = 500;\n");
  std::printf("// Index 0 is unused (official leaves it uninitialised; dof >= 1 always).\n");
  std::printf("constexpr double CHI2_TABLE_95[CHI2_TABLE_SIZE] = {\n    0.0,\n");
  for (int i = 1; i < 500; i++) {
    boost::math::chi_squared d(i);
    double q = boost::math::quantile(d, 0.95);
    std::printf("    %a,%s", q, (i % 4 == 0) ? "\n" : "");
  }
  std::printf("\n};\n\n}  // namespace msckf\n");
  return 0;
}
